## 50 MHz clock
set_property PACKAGE_PIN W5 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports clock]
create_clock -period 20.000 -name clk100MHz -waveform {0.000 10.000} [get_ports clock]

set_property PACKAGE_PIN U16 [get_ports {io_x31[0]}]
set_property PACKAGE_PIN E19 [get_ports {io_x31[1]}]
set_property PACKAGE_PIN U19 [get_ports {io_x31[2]}]
set_property PACKAGE_PIN V19 [get_ports {io_x31[3]}]
set_property PACKAGE_PIN W18 [get_ports {io_x31[4]}]
set_property PACKAGE_PIN U15 [get_ports {io_x31[5]}]
set_property PACKAGE_PIN U14 [get_ports {io_x31[6]}]
set_property PACKAGE_PIN V14 [get_ports {io_x31[7]}]
set_property PACKAGE_PIN V13 [get_ports {io_x31[8]}]
set_property PACKAGE_PIN V3 [get_ports {io_x31[9]}]
set_property PACKAGE_PIN W3 [get_ports {io_x31[10]}]
set_property PACKAGE_PIN U3 [get_ports {io_x31[11]}]
set_property PACKAGE_PIN P3 [get_ports {io_x31[12]}]
set_property PACKAGE_PIN N3 [get_ports {io_x31[13]}]
set_property PACKAGE_PIN P1 [get_ports {io_x31[14]}]
set_property PACKAGE_PIN L1 [get_ports {io_x31[15]}]

set_property PACKAGE_PIN U18 [get_ports reset]
set_property PACKAGE_PIN T18 [get_ports io_write_bit]
set_property IOSTANDARD LVCMOS33 [get_ports {io_x31[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_x31[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_x31[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_x31[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_x31[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_x31[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_x31[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_x31[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_x31[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_x31[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_x31[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_x31[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_x31[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_x31[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_x31[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_x31[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports io_write_bit]
set_property IOSTANDARD LVCMOS33 [get_ports reset]


