// Generated by CIRCT firtool-1.114.1
module Alu(
  input  [31:0] io_src1,
                io_src2,
  input  [3:0]  io_op,
  output [31:0] io_dest,
  output [2:0]  io_flags
);

  wire [62:0]       _io_dest_T_3 = {31'h0, io_src1} << io_src2[4:0];
  wire [15:0][31:0] _GEN =
    {{32'h0},
     {32'h0},
     {$signed($signed(io_src1) >>> io_src2[4:0])},
     {32'h0},
     {32'h0},
     {32'h0},
     {32'h0},
     {io_src1 - io_src2},
     {io_src1 & io_src2},
     {io_src1 | io_src2},
     {io_src1 >> io_src2[4:0]},
     {io_src1 ^ io_src2},
     {{31'h0, io_src1 < io_src2}},
     {{31'h0, $signed(io_src1) < $signed(io_src2)}},
     {_io_dest_T_3[31:0]},
     {io_src1 + io_src2}};
  assign io_dest = _GEN[io_op];
  assign io_flags =
    {io_src1 < io_src2, $signed(io_src1) < $signed(io_src2), io_src1 == io_src2};
endmodule

