// Generated by CIRCT firtool-1.114.1
module Fetch(
  input         clock,
                reset,
  input  [31:0] io_inst_in,
  output [31:0] io_pc,
  output [4:0]  io_hu_src1,
                io_hu_src2,
  input         io_stall,
  output [4:0]  io_src1,
                io_src2,
                io_dest,
  output [31:0] io_imm,
  output [3:0]  io_alu_op,
  output        io_imm_mux,
                io_mem_mux,
  output [1:0]  io_mem_size,
  output        io_mem_sx,
                io_mem_store,
                io_alu_d,
  input         io_jmp_ready,
  input  [31:0] io_jmp_addr,
  input  [2:0]  io_flags
);

  wire        _GEN;
  wire [4:0]  src1;
  wire        _GEN_0;
  wire        _GEN_1;
  wire        _GEN_2;
  wire        jmp_mux;
  wire [31:0] jmp_dest;
  reg  [31:0] pc;
  reg  [31:0] inst;
  wire [31:0] io_pc_0 = jmp_mux ? jmp_dest : pc;
  reg  [31:0] this_pc;
  reg         jmp_state;
  wire        _GEN_3 = inst[6:0] == 7'h37;
  wire        _GEN_4 = inst[6:0] == 7'h17;
  wire        _GEN_5 = inst[6:0] == 7'h6F;
  wire        _GEN_6 = inst[6:0] == 7'h67;
  wire [19:0] _GEN_7 = {20{inst[31]}};
  wire [31:0] sx = {_GEN_7, inst[31:20]};
  wire        _GEN_8 = io_stall | ~(jmp_state & io_jmp_ready);
  wire        _GEN_9 = ~io_stall & jmp_state & io_jmp_ready;
  wire        _GEN_10 = inst[6:0] == 7'h63;
  wire        _GEN_11 = _GEN_3 | _GEN_4;
  assign jmp_dest =
    _GEN_11
      ? 32'h0
      : _GEN_5
          ? {{12{inst[31]}}, inst[19:12], inst[20], inst[30:21], 1'h0} + this_pc
          : _GEN_6
              ? (_GEN_8 ? 32'h0 : io_jmp_addr)
              : _GEN_10
                  ? {{20{inst[31]}}, inst[7], inst[30:25], inst[11:8], 1'h0} + this_pc
                  : 32'h0;
  wire        _GEN_12 = _GEN_10 & ~io_stall & ~jmp_state;
  wire        _GEN_13 = _GEN_3 | _GEN_4 | _GEN_5;
  wire        _GEN_14 = _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6;
  wire        _GEN_15 = _GEN_10 & ~io_stall;
  wire        _GEN_16 = _GEN_6 ? ~io_stall & ~jmp_state : _GEN_15 & ~jmp_state;
  assign jmp_mux =
    ~_GEN_11
    & (_GEN_5
       | (_GEN_6
            ? _GEN_9
            : _GEN_15 & jmp_state & io_jmp_ready
              & (inst[12]
                 ^ (inst[14] ? (inst[13] ? io_flags[2] : io_flags[1]) : io_flags[0]))));
  wire        _GEN_17 = inst[6:0] == 7'h3;
  wire        _GEN_18 = inst[14:12] == 3'h0;
  wire        _GEN_19 = inst[14:12] == 3'h1;
  wire        _GEN_20 = inst[14:12] == 3'h2;
  wire        _GEN_21 = inst[14:12] == 3'h4;
  wire        _GEN_22 = inst[14:12] == 3'h5;
  assign _GEN_2 = _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_10;
  wire        _GEN_23 = inst[6:0] == 7'h23;
  wire        _GEN_24 = _GEN_17 | _GEN_23;
  wire        _GEN_25 = _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_10 | _GEN_17;
  wire        _GEN_26 = inst[6:0] == 7'h13;
  wire        _GEN_27 = _GEN_19 | _GEN_22;
  wire        _GEN_28 = inst[6:0] == 7'h33;
  wire        _GEN_29 = _GEN_26 | _GEN_28;
  assign _GEN_1 = _GEN_17 | _GEN_23 | _GEN_29;
  assign _GEN_0 = _GEN_2 | ~_GEN_1;
  assign src1 = _GEN_0 ? 5'h0 : inst[19:15];
  assign _GEN = _GEN_25 | ~(_GEN_23 | ~(_GEN_26 | ~_GEN_28));
  wire        _GEN_30 = _GEN_10 | _GEN_24;
  wire        _GEN_31 = io_stall | _GEN_2;
  always @(posedge clock) begin
    if (reset) begin
      pc <= 32'h0;
      inst <= 32'h0;
      this_pc <= 32'h0;
      jmp_state <= 1'h0;
    end
    else begin
      if (~io_stall & ~(~_GEN_13 & _GEN_16)) begin
        pc <= io_pc_0 + 32'h4;
        inst <= io_inst_in;
        this_pc <= io_pc_0;
      end
      if (~_GEN_13) begin
        automatic logic _GEN_32;
        _GEN_32 = ~jmp_state | ~io_jmp_ready & jmp_state;
        if (_GEN_6) begin
          if (io_stall) begin
          end
          else
            jmp_state <= _GEN_32;
        end
        else if (_GEN_15)
          jmp_state <= _GEN_32;
      end
    end
  end // always @(posedge)
  assign io_pc = io_pc_0;
  assign io_hu_src1 =
    _GEN_13
      ? src1
      : _GEN_6 | (_GEN_10 ? ~jmp_state | ~_GEN_0 : _GEN_24 | ~_GEN_0)
          ? inst[19:15]
          : 5'h0;
  assign io_hu_src2 =
    (_GEN_14 | (_GEN_10 ? jmp_state : _GEN_17 | ~_GEN_23)) & _GEN ? 5'h0 : inst[24:20];
  assign io_src1 =
    io_stall
      ? 5'h0
      : _GEN_13
          ? src1
          : _GEN_6
              ? ((io_stall ? _GEN_0 : jmp_state & (io_jmp_ready | _GEN_2 | ~_GEN_1))
                   ? 5'h0
                   : inst[19:15])
              : _GEN_12 | ~_GEN_0 ? inst[19:15] : 5'h0;
  assign io_src2 = io_stall | (_GEN_14 | ~_GEN_12) & _GEN ? 5'h0 : inst[24:20];
  assign io_dest =
    io_stall
    | ~(_GEN_13 | ~(_GEN_6 ? _GEN_8 : _GEN_10 | ~(_GEN_17 | ~(_GEN_23 | ~_GEN_29))))
      ? 5'h0
      : inst[11:7];
  assign io_imm =
    io_stall
      ? 32'h0
      : _GEN_3
          ? {inst[31:12], 12'h0}
          : _GEN_4
              ? {inst[31:12], 12'h0} + this_pc
              : _GEN_5
                  ? this_pc + 32'h4
                  : _GEN_6
                      ? (io_stall
                           ? 32'h0
                           : jmp_state ? (io_jmp_ready ? this_pc + 32'h4 : 32'h0) : sx)
                      : _GEN_10
                          ? 32'h0
                          : _GEN_17
                              ? sx
                              : _GEN_23
                                  ? {_GEN_7, inst[31:25], inst[11:7]}
                                  : _GEN_26
                                      ? (_GEN_27 ? {27'h0, inst[24:20]} : sx)
                                      : 32'h0;
  assign io_alu_op =
    io_stall | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_30
      ? 4'h0
      : _GEN_26
          ? {_GEN_27 & inst[30], inst[14:12]}
          : _GEN_28 ? {inst[30], inst[14:12]} : 4'h0;
  assign io_imm_mux =
    ~io_stall
    & (_GEN_13
       | (_GEN_6
            ? ~io_stall & (~jmp_state | io_jmp_ready)
            : ~_GEN_10 & (_GEN_24 | _GEN_26)));
  assign io_mem_mux =
    ~io_stall & (_GEN_13 | (_GEN_6 ? _GEN_9 : ~_GEN_30 & (_GEN_26 | _GEN_28)));
  assign io_mem_size =
    _GEN_31
      ? 2'h0
      : _GEN_17
          ? (_GEN_18
               ? 2'h0
               : _GEN_19 ? 2'h1 : _GEN_20 ? 2'h2 : _GEN_21 ? 2'h0 : {1'h0, _GEN_22})
          : ~_GEN_23 | _GEN_18 ? 2'h0 : _GEN_19 ? 2'h1 : {_GEN_20, 1'h0};
  assign io_mem_sx =
    ~_GEN_31 & _GEN_17 & ~(_GEN_18 | _GEN_19 | _GEN_20) & (_GEN_21 | _GEN_22);
  assign io_mem_store = ~(io_stall | _GEN_25) & _GEN_23;
  assign io_alu_d = ~(io_stall | _GEN_13) & _GEN_16;
endmodule

