// Generated by CIRCT firtool-1.114.1
module HazardUnit(
  input  [4:0] io_src1,
               io_src2,
               io_rd_p0,
  input        io_alu_p0,
  input  [4:0] io_rd_p1,
  output       io_stall
);

  wire [31:0] src1 = 32'h1 << io_src1;
  wire [31:0] src2 = 32'h1 << io_src2;
  wire [31:0] rd_p0 = 32'h1 << io_rd_p0;
  wire [31:0] rd_p1 = 32'h1 << io_rd_p1;
  wire [30:0] overlap_mask = (src1[31:1] | src2[31:1]) & (rd_p0[31:1] | rd_p1[31:1]);
  assign io_stall =
    overlap_mask[0] | overlap_mask[1] | overlap_mask[2] | overlap_mask[3]
    | overlap_mask[4] | overlap_mask[5] | overlap_mask[6] | overlap_mask[7]
    | overlap_mask[8] | overlap_mask[9] | overlap_mask[10] | overlap_mask[11]
    | overlap_mask[12] | overlap_mask[13] | overlap_mask[14] | overlap_mask[15]
    | overlap_mask[16] | overlap_mask[17] | overlap_mask[18] | overlap_mask[19]
    | overlap_mask[20] | overlap_mask[21] | overlap_mask[22] | overlap_mask[23]
    | overlap_mask[24] | overlap_mask[25] | overlap_mask[26] | overlap_mask[27]
    | overlap_mask[28] | overlap_mask[29] | overlap_mask[30] | io_alu_p0;
endmodule

