// Generated by CIRCT firtool-1.114.1
module InOrder(
  input         clock,
                reset,
  input  [31:0] io_inst_in,
  output [31:0] io_pc,
  output [29:0] io_addr,
  input  [31:0] io_read,
  output [31:0] io_write,
                io_write_mask,
                io_rf_0,
                io_rf_1,
                io_rf_2,
                io_rf_3,
                io_rf_4,
                io_rf_5,
                io_rf_6,
                io_rf_7,
                io_rf_8,
                io_rf_9,
                io_rf_10,
                io_rf_11,
                io_rf_12,
                io_rf_13,
                io_rf_14,
                io_rf_15,
                io_rf_16,
                io_rf_17,
                io_rf_18,
                io_rf_19,
                io_rf_20,
                io_rf_21,
                io_rf_22,
                io_rf_23,
                io_rf_24,
                io_rf_25,
                io_rf_26,
                io_rf_27,
                io_rf_28,
                io_rf_29,
                io_rf_30,
                io_rf_31,
  output        io_stall,
  output [4:0]  io_s1_p0,
                io_s2_p0,
                io_rd_p0,
  output [31:0] io_s1_p1,
                io_s2_p1,
  output [4:0]  io_rd_p1,
  output [31:0] io_s1_p2,
                io_s2_p2,
  output [4:0]  io_rd_p2,
  output [31:0] io_debug
);

  wire        _hu_io_stall;
  wire [31:0] _mau_io_read_p2;
  wire [3:0]  _mau_io_write_mask_m;
  wire [31:0] _alu_io_dest;
  wire [2:0]  _alu_io_flags;
  wire [31:0] _rf_io_dests_0;
  wire [31:0] _rf_io_dests_1;
  wire [4:0]  _fetch_io_hu_src1;
  wire [4:0]  _fetch_io_hu_src2;
  wire [4:0]  _fetch_io_src1;
  wire [4:0]  _fetch_io_src2;
  wire [4:0]  _fetch_io_dest;
  wire [31:0] _fetch_io_imm;
  wire [3:0]  _fetch_io_alu_op;
  wire        _fetch_io_imm_mux;
  wire        _fetch_io_mem_mux;
  wire [1:0]  _fetch_io_mem_size;
  wire        _fetch_io_mem_sx;
  wire        _fetch_io_mem_store;
  wire        _fetch_io_alu_d;
  reg  [4:0]  rd_p0;
  reg  [4:0]  r1_p0;
  reg  [4:0]  r2_p0;
  reg  [3:0]  op_p0;
  reg  [31:0] imm_p0;
  reg         imm_mux_p0;
  reg         mem_mux_p0;
  reg  [1:0]  mem_size_p0;
  reg         mem_sx_p0;
  reg         mem_store_p0;
  reg         alu_d_p0;
  reg  [4:0]  rd_p1;
  reg  [31:0] s1_p1;
  reg  [31:0] s2_p1;
  reg  [31:0] imm_p1;
  reg  [3:0]  op_p1;
  reg         imm_mux_p1;
  reg         mem_mux_p1;
  reg  [1:0]  mem_size_p1;
  reg         mem_sx_p1;
  reg         mem_store_p1;
  reg         alu_d_p1;
  reg  [31:0] res_p2;
  reg  [4:0]  rd_p2;
  reg         mem_mux_p2;
  reg  [1:0]  mem_size_p2;
  reg         mem_sx_p2;
  always @(posedge clock) begin
    if (reset) begin
      rd_p0 <= 5'h0;
      r1_p0 <= 5'h0;
      r2_p0 <= 5'h0;
      op_p0 <= 4'h0;
      imm_p0 <= 32'h0;
      imm_mux_p0 <= 1'h0;
      mem_mux_p0 <= 1'h0;
      mem_size_p0 <= 2'h0;
      mem_sx_p0 <= 1'h0;
      mem_store_p0 <= 1'h0;
      alu_d_p0 <= 1'h0;
      rd_p1 <= 5'h0;
      s1_p1 <= 32'h0;
      s2_p1 <= 32'h0;
      imm_p1 <= 32'h0;
      op_p1 <= 4'h0;
      imm_mux_p1 <= 1'h0;
      mem_mux_p1 <= 1'h0;
      mem_size_p1 <= 2'h0;
      mem_sx_p1 <= 1'h0;
      mem_store_p1 <= 1'h0;
      alu_d_p1 <= 1'h0;
      res_p2 <= 32'h0;
      rd_p2 <= 5'h0;
      mem_mux_p2 <= 1'h0;
      mem_size_p2 <= 2'h0;
      mem_sx_p2 <= 1'h0;
    end
    else begin
      rd_p0 <= _fetch_io_dest;
      r1_p0 <= _fetch_io_src1;
      r2_p0 <= _fetch_io_src2;
      op_p0 <= _fetch_io_alu_op;
      imm_p0 <= _fetch_io_imm;
      imm_mux_p0 <= _fetch_io_imm_mux;
      mem_mux_p0 <= _fetch_io_mem_mux;
      mem_size_p0 <= _fetch_io_mem_size;
      mem_sx_p0 <= _fetch_io_mem_sx;
      mem_store_p0 <= _fetch_io_mem_store;
      alu_d_p0 <= _fetch_io_alu_d;
      rd_p1 <= rd_p0;
      s1_p1 <= _rf_io_dests_0;
      s2_p1 <= _rf_io_dests_1;
      imm_p1 <= imm_p0;
      op_p1 <= op_p0;
      imm_mux_p1 <= imm_mux_p0;
      mem_mux_p1 <= mem_mux_p0;
      mem_size_p1 <= mem_size_p0;
      mem_sx_p1 <= mem_sx_p0;
      mem_store_p1 <= mem_store_p0;
      alu_d_p1 <= alu_d_p0;
      res_p2 <= _alu_io_dest;
      rd_p2 <= rd_p1;
      mem_mux_p2 <= mem_mux_p1;
      mem_size_p2 <= mem_size_p1;
      mem_sx_p2 <= mem_sx_p1;
    end
  end // always @(posedge)
  Fetch fetch (
    .clock        (clock),
    .reset        (reset),
    .io_inst_in   (io_inst_in),
    .io_pc        (io_pc),
    .io_hu_src1   (_fetch_io_hu_src1),
    .io_hu_src2   (_fetch_io_hu_src2),
    .io_stall     (_hu_io_stall),
    .io_src1      (_fetch_io_src1),
    .io_src2      (_fetch_io_src2),
    .io_dest      (_fetch_io_dest),
    .io_imm       (_fetch_io_imm),
    .io_alu_op    (_fetch_io_alu_op),
    .io_imm_mux   (_fetch_io_imm_mux),
    .io_mem_mux   (_fetch_io_mem_mux),
    .io_mem_size  (_fetch_io_mem_size),
    .io_mem_sx    (_fetch_io_mem_sx),
    .io_mem_store (_fetch_io_mem_store),
    .io_alu_d     (_fetch_io_alu_d),
    .io_jmp_ready (alu_d_p1),
    .io_jmp_addr  (_alu_io_dest),
    .io_flags     (_alu_io_flags)
  );
  RegisterFile rf (
    .clock           (clock),
    .reset           (reset),
    .io_srcs_0       (r1_p0),
    .io_srcs_1       (r2_p0),
    .io_dests_0      (_rf_io_dests_0),
    .io_dests_1      (_rf_io_dests_1),
    .io_write_reg    (rd_p2),
    .io_write_data   (mem_mux_p2 ? res_p2 : _mau_io_read_p2),
    .io_registers_0  (io_rf_0),
    .io_registers_1  (io_rf_1),
    .io_registers_2  (io_rf_2),
    .io_registers_3  (io_rf_3),
    .io_registers_4  (io_rf_4),
    .io_registers_5  (io_rf_5),
    .io_registers_6  (io_rf_6),
    .io_registers_7  (io_rf_7),
    .io_registers_8  (io_rf_8),
    .io_registers_9  (io_rf_9),
    .io_registers_10 (io_rf_10),
    .io_registers_11 (io_rf_11),
    .io_registers_12 (io_rf_12),
    .io_registers_13 (io_rf_13),
    .io_registers_14 (io_rf_14),
    .io_registers_15 (io_rf_15),
    .io_registers_16 (io_rf_16),
    .io_registers_17 (io_rf_17),
    .io_registers_18 (io_rf_18),
    .io_registers_19 (io_rf_19),
    .io_registers_20 (io_rf_20),
    .io_registers_21 (io_rf_21),
    .io_registers_22 (io_rf_22),
    .io_registers_23 (io_rf_23),
    .io_registers_24 (io_rf_24),
    .io_registers_25 (io_rf_25),
    .io_registers_26 (io_rf_26),
    .io_registers_27 (io_rf_27),
    .io_registers_28 (io_rf_28),
    .io_registers_29 (io_rf_29),
    .io_registers_30 (io_rf_30),
    .io_registers_31 (io_rf_31)
  );
  Alu alu (
    .io_src1  (s1_p1),
    .io_src2  (imm_mux_p1 ? imm_p1 : s2_p1),
    .io_op    (op_p1),
    .io_dest  (_alu_io_dest),
    .io_flags (_alu_io_flags)
  );
  Mau mau (
    .io_addr_p1      (_alu_io_dest),
    .io_addr_p2      (res_p2),
    .io_read_p2      (_mau_io_read_p2),
    .io_write_p1     (s2_p1),
    .io_addr_m       (io_addr),
    .io_read_m       (io_read),
    .io_write_m      (io_write),
    .io_write_mask_m (_mau_io_write_mask_m),
    .io_mem_size_p1  (mem_size_p1),
    .io_mem_store_p1 (mem_store_p1),
    .io_mem_size_p2  (mem_size_p2),
    .io_mem_sx_p2    (mem_sx_p2)
  );
  HazardUnit hu (
    .io_src1   (_fetch_io_hu_src1),
    .io_src2   (_fetch_io_hu_src2),
    .io_rd_p0  (rd_p0),
    .io_alu_p0 (alu_d_p0),
    .io_rd_p1  (rd_p1),
    .io_stall  (_hu_io_stall)
  );
  assign io_write_mask = {28'h0, _mau_io_write_mask_m};
  assign io_stall = _hu_io_stall;
  assign io_s1_p0 = r1_p0;
  assign io_s2_p0 = r2_p0;
  assign io_rd_p0 = rd_p0;
  assign io_s1_p1 = s1_p1;
  assign io_s2_p1 = s2_p1;
  assign io_rd_p1 = rd_p1;
  assign io_s1_p2 = 32'h0;
  assign io_s2_p2 = 32'h0;
  assign io_rd_p2 = rd_p2;
  assign io_debug = _alu_io_dest;
endmodule

