// Generated by CIRCT firtool-1.114.1
module Mau(
  input  [31:0] io_addr_p1,
                io_addr_p2,
  output [31:0] io_read_p2,
  input  [31:0] io_write_p1,
  output [29:0] io_addr_m,
  input  [31:0] io_read_m,
  output [31:0] io_write_m,
  output [3:0]  io_write_mask_m,
  input  [1:0]  io_mem_size_p1,
  input         io_mem_store_p1,
  input  [1:0]  io_mem_size_p2,
  input         io_mem_sx_p2
);

  wire [3:0][7:0]  _GEN =
    {{io_read_m[31:24]}, {io_read_m[23:16]}, {io_read_m[15:8]}, {io_read_m[7:0]}};
  wire [7:0]       byte_0 = _GEN[io_addr_p2[1:0]];
  wire [15:0]      selected_half =
    io_mem_size_p2[0]
      ? (io_addr_p2[1] ? io_read_m[31:16] : io_read_m[15:0])
      : {io_mem_sx_p2 ? {8{byte_0[7]}} : 8'h0, byte_0};
  wire [1:0]       half_oh = 2'h1 << io_addr_p1[1];
  wire [3:0][3:0]  _GEN_0 =
    {{4'h0}, {4'hF}, {{{2{half_oh[1]}}, {2{half_oh[0]}}}}, {4'h1 << io_addr_p1[1:0]}};
  wire [47:0]      _io_write_m_T_11 = {io_write_p1, 16'h0};
  wire [3:0][55:0] _GEN_1 =
    {{56'h0},
     {{24'h0, io_write_p1}},
     {{8'h0, io_addr_p1[1] ? _io_write_m_T_11 : {16'h0, io_write_p1}}},
     {(&(io_addr_p1[1:0]))
        ? {io_write_p1, 24'h0}
        : {8'h0,
           io_addr_p1[1:0] == 2'h2
             ? _io_write_m_T_11
             : {8'h0,
                io_addr_p1[1:0] == 2'h1 ? {io_write_p1, 8'h0} : {8'h0, io_write_p1}}}}};
  assign io_read_p2 =
    io_mem_size_p2[1]
      ? io_read_m
      : {io_mem_sx_p2 ? {16{selected_half[15]}} : 16'h0, selected_half};
  assign io_addr_m = io_addr_p1[31:2];
  assign io_write_m = io_mem_store_p1 ? _GEN_1[io_mem_size_p1][31:0] : 32'h0;
  assign io_write_mask_m = io_mem_store_p1 ? _GEN_0[io_mem_size_p1] : 4'h0;
endmodule

