// Generated by CIRCT firtool-1.114.1
module RegisterFile(
  input         clock,
                reset,
  input  [4:0]  io_srcs_0,
                io_srcs_1,
  output [31:0] io_dests_0,
                io_dests_1,
  input  [4:0]  io_write_reg,
  input  [31:0] io_write_data,
  output [31:0] io_registers_0,
                io_registers_1,
                io_registers_2,
                io_registers_3,
                io_registers_4,
                io_registers_5,
                io_registers_6,
                io_registers_7,
                io_registers_8,
                io_registers_9,
                io_registers_10,
                io_registers_11,
                io_registers_12,
                io_registers_13,
                io_registers_14,
                io_registers_15,
                io_registers_16,
                io_registers_17,
                io_registers_18,
                io_registers_19,
                io_registers_20,
                io_registers_21,
                io_registers_22,
                io_registers_23,
                io_registers_24,
                io_registers_25,
                io_registers_26,
                io_registers_27,
                io_registers_28,
                io_registers_29,
                io_registers_30,
                io_registers_31
);

  reg  [31:0]       registers_1;
  reg  [31:0]       registers_2;
  reg  [31:0]       registers_3;
  reg  [31:0]       registers_4;
  reg  [31:0]       registers_5;
  reg  [31:0]       registers_6;
  reg  [31:0]       registers_7;
  reg  [31:0]       registers_8;
  reg  [31:0]       registers_9;
  reg  [31:0]       registers_10;
  reg  [31:0]       registers_11;
  reg  [31:0]       registers_12;
  reg  [31:0]       registers_13;
  reg  [31:0]       registers_14;
  reg  [31:0]       registers_15;
  reg  [31:0]       registers_16;
  reg  [31:0]       registers_17;
  reg  [31:0]       registers_18;
  reg  [31:0]       registers_19;
  reg  [31:0]       registers_20;
  reg  [31:0]       registers_21;
  reg  [31:0]       registers_22;
  reg  [31:0]       registers_23;
  reg  [31:0]       registers_24;
  reg  [31:0]       registers_25;
  reg  [31:0]       registers_26;
  reg  [31:0]       registers_27;
  reg  [31:0]       registers_28;
  reg  [31:0]       registers_29;
  reg  [31:0]       registers_30;
  reg  [31:0]       registers_31;
  wire [31:0][31:0] _GEN =
    {{registers_31},
     {registers_30},
     {registers_29},
     {registers_28},
     {registers_27},
     {registers_26},
     {registers_25},
     {registers_24},
     {registers_23},
     {registers_22},
     {registers_21},
     {registers_20},
     {registers_19},
     {registers_18},
     {registers_17},
     {registers_16},
     {registers_15},
     {registers_14},
     {registers_13},
     {registers_12},
     {registers_11},
     {registers_10},
     {registers_9},
     {registers_8},
     {registers_7},
     {registers_6},
     {registers_5},
     {registers_4},
     {registers_3},
     {registers_2},
     {registers_1},
     {32'h0}};
  always @(posedge clock) begin
    if (reset) begin
      registers_1 <= 32'h0;
      registers_2 <= 32'h0;
      registers_3 <= 32'h0;
      registers_4 <= 32'h0;
      registers_5 <= 32'h0;
      registers_6 <= 32'h0;
      registers_7 <= 32'h0;
      registers_8 <= 32'h0;
      registers_9 <= 32'h0;
      registers_10 <= 32'h0;
      registers_11 <= 32'h0;
      registers_12 <= 32'h0;
      registers_13 <= 32'h0;
      registers_14 <= 32'h0;
      registers_15 <= 32'h0;
      registers_16 <= 32'h0;
      registers_17 <= 32'h0;
      registers_18 <= 32'h0;
      registers_19 <= 32'h0;
      registers_20 <= 32'h0;
      registers_21 <= 32'h0;
      registers_22 <= 32'h0;
      registers_23 <= 32'h0;
      registers_24 <= 32'h0;
      registers_25 <= 32'h0;
      registers_26 <= 32'h0;
      registers_27 <= 32'h0;
      registers_28 <= 32'h0;
      registers_29 <= 32'h0;
      registers_30 <= 32'h0;
      registers_31 <= 32'h0;
    end
    else begin
      if ((|io_write_reg) & io_write_reg == 5'h1)
        registers_1 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'h2)
        registers_2 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'h3)
        registers_3 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'h4)
        registers_4 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'h5)
        registers_5 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'h6)
        registers_6 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'h7)
        registers_7 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'h8)
        registers_8 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'h9)
        registers_9 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'hA)
        registers_10 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'hB)
        registers_11 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'hC)
        registers_12 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'hD)
        registers_13 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'hE)
        registers_14 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'hF)
        registers_15 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'h10)
        registers_16 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'h11)
        registers_17 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'h12)
        registers_18 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'h13)
        registers_19 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'h14)
        registers_20 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'h15)
        registers_21 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'h16)
        registers_22 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'h17)
        registers_23 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'h18)
        registers_24 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'h19)
        registers_25 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'h1A)
        registers_26 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'h1B)
        registers_27 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'h1C)
        registers_28 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'h1D)
        registers_29 <= io_write_data;
      if ((|io_write_reg) & io_write_reg == 5'h1E)
        registers_30 <= io_write_data;
      if ((|io_write_reg) & (&io_write_reg))
        registers_31 <= io_write_data;
    end
  end // always @(posedge)
  assign io_dests_0 = _GEN[io_srcs_0];
  assign io_dests_1 = _GEN[io_srcs_1];
  assign io_registers_0 = 32'h0;
  assign io_registers_1 = registers_1;
  assign io_registers_2 = registers_2;
  assign io_registers_3 = registers_3;
  assign io_registers_4 = registers_4;
  assign io_registers_5 = registers_5;
  assign io_registers_6 = registers_6;
  assign io_registers_7 = registers_7;
  assign io_registers_8 = registers_8;
  assign io_registers_9 = registers_9;
  assign io_registers_10 = registers_10;
  assign io_registers_11 = registers_11;
  assign io_registers_12 = registers_12;
  assign io_registers_13 = registers_13;
  assign io_registers_14 = registers_14;
  assign io_registers_15 = registers_15;
  assign io_registers_16 = registers_16;
  assign io_registers_17 = registers_17;
  assign io_registers_18 = registers_18;
  assign io_registers_19 = registers_19;
  assign io_registers_20 = registers_20;
  assign io_registers_21 = registers_21;
  assign io_registers_22 = registers_22;
  assign io_registers_23 = registers_23;
  assign io_registers_24 = registers_24;
  assign io_registers_25 = registers_25;
  assign io_registers_26 = registers_26;
  assign io_registers_27 = registers_27;
  assign io_registers_28 = registers_28;
  assign io_registers_29 = registers_29;
  assign io_registers_30 = registers_30;
  assign io_registers_31 = registers_31;
endmodule

